name: Changelog Generator

on:
  push:
    branches: [ main ]

jobs:
  generate_changelog_file:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Generate changelog
      uses: browniebroke/action-github-changelog-generator@v2.1.1
      with:
        token: ${{ secrets.GH_TOKEN }}
        author: true
        unreleased: true
        issues: true
        pullRequests: true
        prWoLabels: false
        compareLink: true
        output: CHANGELOG.md
        breakingLabel: ":boom: Breaking Changes:"
        breakingLabels: "breaking"
        deprecatedLabel: ":fire: Removals"
        deprecatedLabels: "removal"
        enhancementLabel: ":rocket: Features and Enhancements:"
        enhancementLabels: "enhancement"
        bugLabel: ":beetle: Bug Fixes:"
        bugLabels: "bug,bug-fix,fix,fixes"
        removedLabel: ':wastebasket: Removals:'
        removedLabels: 'removal'
        addSections: '{"documentation":{"prefix":"Documentation updates","labels":["documentation"]},"style":{"prefix":"Style","labels":["style"]},"dependencies":{"prefix":"Dependencies","labels":["dependencies"]},"refactoring":{"prefix":"Refactoring","labels":["refactoring"]},"ci":{"prefix":"Build and CI","labels":["ci", "build"]}}'
        # See: emojipedia.org for emoji codes
    - name: Commit CHANGELOG.md
      uses: EndBug/add-and-commit@v7 # You can change this to use a specific version
      if: success()
      with:
        add: 'CHANGELOG.md'
